CREATE TABLE IF NOT EXISTS STUDENTS (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENTS (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('001', 'Aditya Suthar', 'Vadodara', '1234567890', 15),
('002', 'Krisha Patel', 'Vadodara', '0987654321', 15),
('003', 'Vyom Varia', 'Ahmedabad', '1122334455', 16);

SELECT * from STUDENTS;

SELECT * FROM STUDENTS WHERE AGE > 15;

SELECT * FROM STUDENTS WHERE AGE = 15;

SELECT * FROM STUDENTS WHERE AGE = 15 AND ADDRESS = 'Vadodara';

SELECT * FROM STUDENTS WHERE NAME = 'Aditya Suthar' OR NAME = 'Krisha Patel';

SELECT * FROM STUDENTS WHERE NAME = 'Vyom Varia' OR NAME = 'Aditya Suthar';

SELECT * FROM STUDENTS WHERE AGE = 15 AND (ROLL_NO = '001' OR ROLL_NO = '002');